array_width = 120
array_fn_like_width = 120
brace_style = "PreferSameLine"
chain_width = 120
comment_width = 120
edition = "2021"
fn_params_layout = "Compressed"
fn_call_width = 120
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
max_width = 120
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
short_array_element_width_threshold = 40
single_line_if_else_max_width = 120
struct_lit_width = 40
struct_variant_width = 80
tab_spaces = 2
unstable_features = true
use_field_init_shorthand = true
version = "Two"
where_single_line = true
wrap_comments = true

