[package]
name = "cantrip"
version = "0.0.0"
edition = "2021"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"

[build]
rustflags = [
  "-W absolute-paths-not-starting-with-crate",
  "-W box_pointers",
  "-W elided-lifetimes-in-paths",
  "-W explicit-outlives-requirements",
  "-W ffi-unwind-calls",
  "-W fuzzy_provenance_casts",
  "-W keyword-idents",
  "-W let-underscore-drop ",
  "-W lossy-provenance-casts",
  "-W macro-use-extern-crate",
  "-W meta-variable-misuse",
  "-W missing-abi",
  "-W missing-copy-implementations",
  "-W missing-debug-implementations",
  "-W missing-docs",
  "-W multiple-supertrait-upcastable",
  "-W must-not-suspend",
  "-W non_ascii_idents",
  "-W non_exhaustive_omitted_patterns",
  "-W noop_method_call",
  "-W pointer_structural_match",
  "-W rust_2021_incompatible_closure_captures",
  "-W rust_2021_incompatible_or_patterns",
  "-W rust_2021_prefixes_incompatible_syntax",
  "-W rust_2021_prelude_collisions",
  "-W single_use_lifetimes",
  "-W trivial_casts",
  "-W trivial_numeric_casts",
  "-W unreachable_pub",
  "-W unsafe_code",
  "-W unsafe_op_in_unsafe_fn",
  "-W unstable_features",
  "-W unused_crate_dependencies",
  "-W unused_extern_crates",
  "-W unused_import_braces",
  "-W unused_lifetimes",
  "-W unused_macro_rules",
  "-W unused_qualifications",
  "-W unused_results",
  "-W unused_tuple_struct_fields",
  "-W variant_size_differences"
]
incremental = true

[profile.dev]
opt-level = 1
lto = false

[profile.release]
opt-level = 3
lto = true

