[env]
RUST_BACKTRACE = "1"
RUSTFLAGS = "-D warnings -W absolute-paths-not-starting-with-crate -W box_pointers -W dead_code -W elided-lifetimes-in-paths -W explicit-outlives-requirements -W ffi-unwind-calls -W keyword-idents -W let-underscore-drop -W macro-use-extern-crate -W meta-variable-misuse -W missing-abi -W missing-copy-implementations -W missing-debug-implementations -W missing-docs -W non_ascii_idents -W noop_method_call -W pointer_structural_match -W rust_2021_incompatible_closure_captures -W rust_2021_incompatible_or_patterns -W rust_2021_prefixes_incompatible_syntax -W rust_2021_prelude_collisions -W single_use_lifetimes -W trivial_casts -W trivial_numeric_casts -W unreachable_pub -W unsafe_code -W unsafe_op_in_unsafe_fn -W unstable_features -W unused_crate_dependencies -W unused_extern_crates -W unused_import_braces -W unused_lifetimes -W unused_macro_rules -W unused_qualifications -W unused_results -W variant_size_differences"

[tasks.compile]
command = "cargo"
args = ["build"]

[tasks.check]
command = "cargo"
args = ["clippy"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.retest]
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "-c", "-w", "src", "-w", "tests", "-x", "clippy", "-x", "test"]

[tasks.bench]
command = "cargo"
args = ["bench"]

[tasks.publish]
install_crate = "cargo-release"
command = "cargo"
args = ["publish", "--allow-dirty"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
dependencies = [
  "compile",
  "check",
  "test"
]

