[build]
rustflags = [
  "-Dwarnings",
  "-Wclippy::all",
  "-Wclippy::pedantic",
  "-Wabsolute_paths_not_starting_with_crate",
  "-Wambiguous_negative_literals",
  "-Wclosure_returning_async_block",
  "-Wdeprecated_safe_2024",
  "-Wderef_into_dyn_supertrait",
  "-Wedition_2024_expr_fragment_specifier",
  "-Welided_lifetimes_in_paths",
  "-Wexplicit_outlives_requirements",
  "-Wffi_unwind_calls",
  "-Wif_let_rescope",
  "-Wimpl_trait_overcaptures",
  "-Wimpl_trait_redundant_captures",
  "-Wkeyword-idents",
  "-Wkeyword_idents_2018",
  "-Wkeyword_idents_2024",
  "-Wlet_underscore_drop",
  "-Wlinker_messages",
  "-Wmacro_use_extern_crate",
  "-Wmeta_variable_misuse",
  "-Wmissing_copy_implementations",
  "-Wmissing_debug_implementations",
  "-Wmissing_docs",
  "-Wmissing_unsafe_on_extern",
  "-Wnon_ascii_idents",
  "-Wredundant_imports",
  "-Wredundant_lifetimes",
  "-Wrust_2021_incompatible_closure_captures",
  "-Wrust_2021_incompatible_or_patterns",
  "-Wrust_2021_prefixes_incompatible_syntax",
  "-Wrust_2021_prelude_collisions",
  "-Wrust_2024_guarded_string_incompatible_syntax",
  "-Wrust_2024_incompatible_pat",
  "-Wrust_2024_prelude_collisions",
  "-Wsingle_use_lifetimes",
  "-Wtail_expr_drop_order",
  "-Wtrivial_casts",
  "-Wtrivial_numeric_casts",
  "-Wunit_bindings",
  "-Wunnameable_types",
  "-Wunreachable_pub",
  "-Wunsafe_attr_outside_unsafe",
  "-Wunsafe_code",
  "-Wunsafe_op_in_unsafe_fn",
  "-Wunstable_features",
  "-Wunused_crate_dependencies",
  "-Wunused_extern_crates",
  "-Wunused_import_braces",
  "-Wunused_lifetimes",
  "-Wunused_macro_rules",
  "-Wunused_qualifications",
  "-Wunused_results",
  "-Wvariant_size_differences"
]
