name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags: [ v* ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read

concurrency:
  group: 'build'
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
          key: cargo-${{ runner.os }}-${{ hashFiles('**/*.toml') }}

      - name: Build project
        run: cargo test --all-features

