name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags: [ v* ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

permissions:
  contents: read

concurrency:
  group: 'build'
  cancel-in-progress: false

jobs:
  build:
    name: Build (${{ matrix.toolchain }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, beta]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy
      - run: cargo clippy --verbose
      - run: cargo build --verbose
      - run: cargo test --release --all-features --verbose
